#!/usr/bin/env bash

step="MiniAOD Production"
echo "Run ${step}."

cmsDriver.py step1 \
    --filein file:../../evts_7hlt.root \
    --fileout file:../../evts_8aod.root \
    --mc \
    --eventcontent MINIAODSIM \
    --runUnscheduled \
    --datatier MINIAODSIM \
    --conditions 80X_mcRun2_asymptotic_v14 \
    --customise_commands "process.patTrigger.processName = cms.string('HLT2')" \
    --step PAT \
    --era Run2_2016 \
    --python_filename miniaod_cfg.py \
    --number=-1 \
    --no_exec

return_value_config="$?"

cmsRun miniaod_cfg.py

return_value_cmsRun="$?"
echo "Return value from ${step} config: ${return_value_config}"
echo "Return value from ${step} cmsRun: ${return_value_cmsRun}"

# Return larger return value
if [ "${return_value_config}" -ge "${return_value_cmsRun}" ]; then
    exit "${return_value_config}"
else
    exit "${return_value_cmsRun}"
fi
