#!/usr/bin/env bash

set -euf -o pipefail

step="Reconstruction"
echo "Run ${step}."

cmsDriver.py step2 \
    --filein file:../../evts_5raw.root \
    --fileout file:../../evts_6rec.root \
    --mc \
    --eventcontent RAWAODSIM \
    --runUnscheduled \
    --datatier RAWAODSIM \
    --conditions 80X_mcRun2_asymptotic_2016_v3 \
    --step RAW2DIGI,L1Reco,RECO,EI \
    --era Run2_25ns \
    --python_filename cfg_reconstruction.py \
    --number=-1 \
    --no_exec
