#!/usr/bin/env bash

step="Digitization"
echo "Run ${step}."

cmsDriver.py step1 \
    --filein file:../../evts_3sim.root \
    --fileout file:../../evts_5raw.root \
    --pileup_input dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIISummer15GS-MCRUN2_71_V1-v2/GEN-SIM \
    --mc \
    --eventcontent RAWSIM \
    --pileup 2016_25ns_SpringMC_PUScenarioV1_PoissonOOTPU \
    --datatier GEN-SIM-RAW \
    --conditions 80X_mcRun2_asymptotic_2016_v3 \
    --customise_commands "process.simHcalDigis.markAndPass = cms.bool(True)" \
    --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns \
    --era Run2_25ns \
    --python_filename digitization_cfg.py \
    --number=-1 \
    --no_exec

return_value_config="$?"

cmsRun digitization_cfg.py

return_value_cmsRun="$?"
echo "Return value from ${step} config: ${return_value_config}"
echo "Return value from ${step} cmsRun: ${return_value_cmsRun}"

# Return larger return value
if [ "${return_value_config}" -ge "${return_value_cmsRun}" ]; then
    return "${return_value_config}"
else
    return "${return_value_cmsRun}"
fi
