#!/usr/bin/env bash

step="Reconstruction"
echo "Run ${step}."

cmsDriver.py step2 \
    --filein file:../../evts_5raw.root \
    --fileout file:../../evts_6rec.root \
    --mc \
    --eventcontent RAWAODSIM \
    --runUnscheduled \
    --datatier RAWAODSIM \
    --conditions 80X_mcRun2_asymptotic_2016_v3 \
    --step RAW2DIGI,L1Reco,RECO,EI \
    --era Run2_25ns \
    --python_filename reconstruction_cfg.py \
    --number=-1 \
    --no_exec

return_value_config="$?"

cmsRun reconstruction_cfg.py

return_value_cmsRun="$?"
echo "Return value from ${step} config: ${return_value_config}"
echo "Return value from ${step} cmsRun: ${return_value_cmsRun}"

# Return larger return value
if [ "${return_value_config}" -ge "${return_value_cmsRun}" ]; then
    return "${return_value_config}"
else
    return "${return_value_cmsRun}"
fi
