#!/usr/bin/env bash

set -euf -o pipefail

nEvents="${1:--1}"

step="Generation to HLT"
echo "Run steps ${step}."

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/Hadronizer_TuneCUETP8M1_13TeV_generic_LHE_pythia8_cff.py \
    --filein file:../../input.lhe \
    --fileout file:../../evts_7hlt.root \
    --mc \
    --pileup_input "dbs:/Neutrino_E-10_gun/RunIISummer17PrePremix-MC_v2_94X_mc2017_realistic_v9-v1/GEN-SIM-DIGI-RAW" \
    --eventcontent AODSIM \
    --fast \
    --customise SimGeneral/DataMixingModule/customiseForPremixingInput.customiseForPreMixingInput,Configuration/DataProcessing/Utils.addMonitoring \
    --datatier AODSIM \
    --conditions 80X_mcRun2_asymptotic_v12 \
    --beamspot Realistic50ns13TeVCollision \
    --customise_commands "process.source.numberEventsInLuminosityBlock = cms.untracked.uint32(200)" \
    --step GEN,SIM,RECOBEFMIX,DIGIPREMIX_S2,DATAMIX,L1,DIGI2RAW,L1Reco,RECO,HLT:@fake1 \
    --datamix PreMix \
    --era Run2_25ns \
    --python_filename cfg_gensimdigirecohlt.py \
    --number "${nEvents}" \
    --no_exec

echo -n "Adding analysis specific lines... "

sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '24:mMin = 0.1'," cfg_gensimdigirecohlt.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '23:mMin = 0.1'," cfg_gensimdigirecohlt.py

## Filter specific lines
#sed -i "/# Production Info/i\
#        # Filter\nprocess.genlep = cms.EDFilter(\"GenParticleSelector\",\n    src = cms.InputTag(\"genParticles\"),\n    cut = cms.string(\"(abs(pdgId) == 11 || abs(pdgId) == 13 || abs(pdgId) == 15) && status == 1 && pt > 3 && abs(eta) < 2.5\"),\n    filter = cms.bool(True),\n)\n\nprocess.genlepfilter = cms.EDFilter(\"CandViewCountFilter\",\n    src = cms.InputTag(\"genlep\"),\n    minNumber = cms.uint32(2),\n)\n\nprocess.lepfilter = cms.Sequence(process.genlep+process.genlepfilter)\n\n" cfg_hadronization.py
#sed -i "s/process\.pgen/&*process.lepfilter/" cfg_hadronization.py

echo "Done."
