#!/usr/bin/env bash

set -euf -o pipefail

nEvents="${1:--1}"

step="Hadronization"
echo "Run ${step}."

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/Hadronizer_TuneCUETP8M1_13TeV_generic_LHE_pythia8_cff.py \
    --filein file:../../input.lhe \
    --fileout file:../../evts_3sim.root \
    --mc \
    --eventcontent RAWSIM \
    --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 \
    --datatier GEN-SIM \
    --conditions MCRUN2_71_V1::All \
    --beamspot Realistic50ns13TeVCollision \
    --step GEN,SIM \
    --magField 38T_PostLS1 \
    --python_filename cfg_hadronization.py \
    --number="${nEvents}" \
    --no_exec

echo -n "Adding analysis specific lines... "

sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ 'Check:abortIfVeto = on'," cfg_hadronization.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '24:mMin = 0.1'," cfg_hadronization.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '23:mMin = 0.1'," cfg_hadronization.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '23:onIfAny = 11 13 15'," cfg_hadronization.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '23:onMode = off'," cfg_hadronization.py

# Filter specific lines
sed -i "/# Production Info/i\
        # Filter\nprocess.genlep = cms.EDFilter(\"GenParticleSelector\",\n    src = cms.InputTag(\"genParticles\"),\n    cut = cms.string(\"(abs(pdgId) == 11 || abs(pdgId) == 13 || abs(pdgId) == 15) && status == 1 && pt > 3 && abs(eta) < 2.5\"),\n    filter = cms.bool(True),\n)\n\nprocess.genlepfilter = cms.EDFilter(\"CandViewCountFilter\",\n    src = cms.InputTag(\"genlep\"),\n    minNumber = cms.uint32(2),\n)\n\nprocess.lepfilter = cms.Sequence(process.genlep+process.genlepfilter)\n\n" cfg_hadronization.py
sed -i "s/process\.pgen/&*process.lepfilter/" cfg_hadronization.py

echo "Done."
