#!/usr/bin/env bash

set -euf -o pipefail

inputfile="${1}"

cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/Hadronizer_TuneCUETP8M1_13TeV_generic_LHE_pythia8_cff.py \
    --filein file:"${inputfile}" \
    --fileout file:../../evts_3sim.root \
    --mc \
    --eventcontent RAWSIM \
    --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 \
    --datatier GEN-SIM \
    --conditions MCRUN2_71_V1::All \
    --beamspot Realistic50ns13TeVCollision \
    --step GEN,SIM \
    --magField 38T_PostLS1 \
    --python_filename hadronizer_cfg.py \
    --number=-1 \
    --no_exec

echo -n "Adding analysis specific lines... "

sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ 'Check:abortIfVeto = on'," hadronizer_cfg.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '24:mMin = 0.1'," hadronizer_cfg.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '23:mMin = 0.1'," hadronizer_cfg.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '23:onIfAny = 11 13 15'," hadronizer_cfg.py
sed -i "/SLHA:minMassSM/a \
        \ \ \ \ \ \ \ \ \ \ \ \ '23:onMode = off'," hadronizer_cfg.py

echo "Done."

cmsRun hadronizer_cfg.py
