#!/usr/bin/env bash

set -euf -o pipefail

nEvents="${1:--1}"

step="Generation to HLT"
echo "Run steps ${step}."

genfrag=Configuration/GenProduction/python/SUS-RunIISummer16FSPremix-00001-fragment.py

# For TChiWZ
# From https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_setup/SUS-RunIISummer16FSPremix-00001
# and https://cms-pdmv.cern.ch/mcm/requests?dataset_name=SMS-TChiWZ_ZToLL_mZMin-0p1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8&page=0&shown=127
curl \
    -s \
    --insecure \
    https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/SUS-RunIISummer16FSPremix-00001 \
    --retry 2 \
    --create-dirs \
    -o "${genfrag}"

if [ ! -s "${genfrag}" ]; then
    echo "Could not download gen fragment."
    echo "Exit."
    exit 1
fi

# Global modifications to generator fragment
# Remove filter
sed -i '/23:onMode/d' "${genfrag}"
sed -i '/23:onIfAny/d' "${genfrag}"

# Set mass points
sed -i '/for col in cols: mpoints.extend(col)/ampoints=[[500,0,50]]\nprint "Points to run:", mpoints' "${genfrag}"

cmsDriver.py "${genfrag}" \
    --fileout file:../../evts_7hlt.root \
    --mc \
    --pileup_input "dbs:/Neutrino_E-10_gun/RunIISummer16FSPremix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v4-v1/GEN-SIM-DIGI-RAW" \
    --eventcontent AODSIM \
    --fast \
    --customise SimGeneral/DataMixingModule/customiseForPremixingInput.customiseForPreMixingInput,Configuration/DataProcessing/Utils.addMonitoring \
    --datatier AODSIM \
    --conditions 80X_mcRun2_asymptotic_2016_TrancheIV_v6 \
    --beamspot Realistic50ns13TeVCollision \
    --customise_commands "process.source.numberEventsInLuminosityBlock = cms.untracked.uint32(2000)" \
    --step GEN,SIM,RECOBEFMIX,DIGIPREMIX_S2,DATAMIX,L1,DIGI2RAW,L1Reco,RECO,HLT:@fake1 \
    --datamix PreMix \
    --era Run2_2016 \
    --python_filename cfg_gensimdigirecohlt.py \
    --number "${nEvents}" \
    --no_exec
